apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  namespace: todoapp
  labels:
    app: todolist
spec:
  containers:
    - name: busybox-co
      image: ikulyk404/busyboxplus:curl
      args:
      - sleep
      - "1000"
