apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  namespace: todoapp
spec:
  type: NodePort
  selector:
    app: todolist
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31111
