apiVersion: v1
kind: Pod
metadata:
  name: todoapp-pod1
  namespace: todoapp
  labels:
    app: todolist
spec:
  containers:
  - name: todoapp
    image: trinida/todoapp:4.0.1
    ports:
    - containerPort: 8080
    env:
    - name: EXTERNAL_ENDPOINT
      value: "http://httpbin-api.todoapp.svc.cluster.local"
    livenessProbe:
      httpGet:
        path: api/health
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: api/ready
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5

---

apiVersion: v1
kind: Pod
metadata:
  name: todoapp-pod2
  namespace: todoapp
  labels:
    app: todolist
spec:
  containers:
  - name: todoapp
    image: trinida/todoapp:4.0.1
    ports:
    - containerPort: 8080
    env:
    - name: EXTERNAL_ENDPOINT
      value: "http://httpbi-api.todoapp.svc.cluster.local"
    livenessProbe:
      httpGet:
        path: api/health
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: api/ready
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
